config/routes.rb
Rails.application.routes.draw do

  
  devise_for :users
  resources :posts do
    resources :comments
  end

  resources :posts do
    member do
    put "like", to: "posts#upvote"
  end
  end
  root "posts#index"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
acts_as_votable
    belongs_to :user
	has_many :comments, dependent: :destroy
	

	validates_presence_of :title, :body
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :posts
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(params[:comment].permit(:name, :body))

		redirect_to post_path(@post)
	end

	def destroy
		@post = Post.find(params[:post_id])
		@comment =@post.comments.find(params[:id])
		@comment.destroy
		redirect_to post_path(@post)
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	before_action :authenticate_user!
  
	def index
		@posts = Post.all.order('created_at DESC')
	end

	def new
		@post = Post.new
	end

	def create
		@post =Post.new(post_params)
		 if @post.save
		redirect_to @post
	    else
	    	render "new"
	    end
	end

	def show
		@post = Post.find(params[:id])
	end
	def edit
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])
		if @post.update(params[:post].permit(:title, :body))
			redirect_to @post
		else
			render "edit"
		end
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy
		redirect_to posts_path
	end

	def upvote
		 @post = Post.find(params[:id])
		@post.upvote_by current_user
		redirect_to :back
	end

	private
	def post_params
		params.require(:post).permit(:title, :body)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="comment clearfix">
<div class="comment_content">
<p class="comment_name"><strong><%= comment.name %></strong></p>
<p class="comment_body"><%= comment.body %></p>
<p class="comment_time"><%= time_ago_in_words(comment.created_at) %> Ago </p>
</div>
<p><%= link_to "Delete", [comment.post,comment],
                method: :delete,
                class: "button",
                data: {confirm: "Are you sure?"}, class: "btn btn-primary" %>
                </p>
      
</div>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>

<p>
<%= f.label :name %><br/>
<%= f.text_field :name %>
</p>

<p>
<%= f.label :body %><br/>
<%= f.text_area :body %>
</p><br/>

<p>
<%= f.submit %>
</p>


<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>



  <%= csrf_meta_tags %>
</head>
<body>
<div class = "container">
<% if user_signed_in? %>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">What I did Interesting today</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Blog</a>
    </div>
    <nav>
    <!-- Collect the nav links, forms, and other content for toggling -->
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "New Post", new_post_path %></li>
        
        <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
          
       </ul>
       </nav>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>


<!--
<div id="sidebar">
    <div id="logo">
    <%#= link_to root_path do %>
    <%#=  image_tag "logo.svg" %>
    <%# end %>
    <ul>
    <li class="category">Website</li>
    <li><%#= link_to "Blog", root_path %></li>
    <li>About </li>
    </ul>
    <p class="sign_in">Admin Login</p>
    </div>
</div>-->
<!--<div id="main_content">
<div id="header">
<p>All posts</p>
<div class="buttons">
<button class="button"><%#= link_to "New Post" new_post_path %></button>
<button class="button">LogOut</button>
</div>
</div>-->
<% if notice %>
 <div class="alert alert-success" role= "alert"><%= notice %></div>
 <% end %>

 <% if alert %>
 <div class="alert alert-danger" role= "alert"><%= alert %></div>
 <% end %>


<% else %>


<% end %>


<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<p><%= form_for @post do |f| %>
<% if @post.errors.any? %>
<div id="errors">
<h2><%= pluralize(@post.errors.count, "error") %>prevented this post from saving</h2>
<ul><% @post.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
</ul>
</div>
<% end %>
<%= f.label :title %><br/>
<%= f.text_field :title %><br/>
</p>

<p>
<%= f.label :body %><br/>
<%= f.text_area :body %><br/>
</p>
<p>
<%= f.submit %>
</p>

<% end %>

app/views/posts/edit.html.erb
<div id="page_wrapper">
<h4>Edit post</h4>

<%= render "form" %>
</div>

app/views/posts/index.html.erb
<div class= "row">
<div class= "col-md-12">
<div class= "page-header">
<% @posts.each do |post| %>

<div class="post_wrapper">
<h2 class ="title">
<%= link_to post.title, post %></h2>

<h5 class = "body">
<p><%= post.body %></p></h5>
<h6>
<p class ="date">posted <%= post.created_at.strftime("%B, %d, %Y") %></p>
</h6>
<%= link_to like_post_path(post), method: :put, class: "btn btn-info" do %>
<span class= "glyphicon glyphicon-heart"></span> Like
<%= post.get_upvotes.size %>
<% end %>
<button type="button" class="btn btn-primary">
  <span class="glyphicon glyphicon-tags"></span>
  <%= post.comments.count %> Comments
</button>

</div> 

<% end %>

</div></div></div>

app/views/posts/new.html.erb
 

<div id="page_wrapper">
<h4>New post</h4>

<%= render "form" %>
</div>

app/views/posts/show.html.erb
<h1 class="title">
<%= @post.title %>
</h1>

<p class="date">
Submitted <%= time_ago_in_words(@post.created_at) %> Ago<br/><br/>
<%= link_to like_post_path(@post), method: :put, class: "btn btn-info" do %>
<span class= "glyphicon glyphicon-heart"></span> Like
<%= @post.get_upvotes.size %>
<% end %>

| <%= link_to "Edit", edit_post_path(@post), class: "btn btn-info" %> 
| <%= link_to "Delete", post_path(@post.id), data: {method: :delete, confirm: "Are you sure?"}, class: "btn btn-info" %>
 
</p>

<p class="body">
<%= @post.body %>
</p>

<div id="comments">
<h2><%= @post.comments.count %> Comments</h2>
<%= render @post.comments %>

<h3>Add a comment</h3>
<%= render "comments/form" %>

</div>